name: triple
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1=he0c23c2_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h477c42c_1
  - dav1d=1.2.1=hcfcfb64_0
  - ffmpeg=8.0.1=gpl_ha36faaf_108
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - gdk-pixbuf=2.44.4=h1f5b9c4_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - glib=2.86.3=h19e2e61_0
  - glib-tools=2.86.3=he647baa_0
  - glslang=16.1.0=h5b34520_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=12.2.0=h5a1b470_1
  - icu=78.1=h637d24d_0
  - lame=3.100=hcfcfb64_1003
  - lerc=4.0.0=h6470a55_1
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.86.3=h0c9aed9_0
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblzma=5.8.1=h2466b09_2
  - libogg=1.3.5=h2466b09_1
  - libopus=1.6=h6a83c73_0
  - libpng=1.6.53=h7351971_0
  - librsvg=2.60.0=hd5e4115_0
  - libsqlite=3.51.1=hf5d6505_1
  - libtiff=4.7.1=h8f73337_1
  - libusb=1.0.29=h1839187_0
  - libvorbis=1.3.7=h5112557_2
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libzlib=1.3.1=h2466b09_2
  - openh264=2.6.0=hb17fa0b_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=h03d888a_0
  - pcre2=10.47=hd2b5f0e_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - python=3.11.14=h0159041_2_cpython
  - sdl2=2.32.56=h5112557_0
  - sdl3=3.2.28=h5112557_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.5=haa9a63f_0
  - spirv-tools=2025.4=h49e36cd_0
  - svt-av1=3.1.2=hac47afa_0
  - tk=8.6.13=h2c6b04d_3
  - tzdata=2025c=h8577fbf_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - vs2015_runtime=14.44.35208=h38c0c73_33
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - zstd=1.5.7=h534d264_6
  - pip:
      - absl-py==2.3.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - audioread==3.1.0
      - bcrypt==5.0.0
      - cachetools==6.2.4
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - cryptography==46.0.3
      - decorator==4.4.2
      - deprecation==2.1.0
      - distro==1.9.0
      - ecdsa==0.19.1
      - fastapi==0.127.0
      - filelock==3.20.1
      - flatbuffers==25.12.19
      - fsspec==2025.12.0
      - greenlet==3.3.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hyperframe==6.1.0
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.46.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mediapipe==0.10.31
      - mmh3==5.2.0
      - more-itertools==10.8.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - networkx==3.6.1
      - numba==0.63.1
      - numpy==2.2.6
      - openai==2.14.0
      - openai-whisper==20250625
      - opencv-python==4.12.0.88
      - passlib==1.7.4
      - pillow==11.3.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - postgrest==2.27.0
      - proglog==0.1.12
      - propcache==0.4.1
      - psycopg2-binary==2.9.11
      - pyasn1==0.6.1
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pygments==2.19.2
      - pyiceberg==0.10.0
      - pyjwt==2.10.1
      - pyparsing==3.3.1
      - pyroaring==1.0.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-jose==3.5.0
      - python-multipart==0.0.21
      - realtime==2.27.0
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rsa==4.9.1
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sounddevice==0.5.3
      - soundfile==0.13.1
      - soxr==1.0.0
      - sqlalchemy==2.0.45
      - starlette==0.50.0
      - storage3==2.27.0
      - strenum==0.4.15
      - strictyaml==1.7.3
      - supabase==2.27.0
      - supabase-auth==2.27.0
      - supabase-functions==2.27.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - torch==2.9.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - websockets==15.0.1
      - yarl==1.22.0
prefix: C:\Users\user\anaconda3\envs\triple
